from typing import Literal

GooglePlaceType = Literal[
    # Food & drink
    "restaurant",
    "cafe",
    "bar",
    "bakery",
    "meal_delivery",
    "meal_takeaway",
    "ice_cream_shop",
    # Shopping
    "shopping_mall",
    "supermarket",
    "grocery_store",
    "convenience_store",
    "clothing_store",
    "shoe_store",
    "electronics_store",
    "cell_phone_store",
    "hardware_store",
    "home_goods_store",
    "furniture_store",
    "jewelry_store",
    "book_store",
    "gift_shop",
    "pet_store",
    "sporting_goods_store",
    # Health
    "hospital",
    "pharmacy",
    "doctor",
    "dentist",
    "medical_lab",
    "physiotherapist",
    "veterinary_care",
    # Finance
    "bank",
    "atm",
    # Travel / accommodation
    "hotel",
    "motel",
    "hostel",
    "bed_and_breakfast",
    "resort_hotel",
    # Transportation
    "airport",
    "bus_station",
    "train_station",
    "subway_station",
    "transit_station",
    "parking",
    "gas_station",
    "car_dealer",
    "car_rental",
    "car_repair",
    "taxi_stand",
    # Education
    "school",
    "primary_school",
    "secondary_school",
    "university",
    "library",
    # Entertainment
    "movie_theater",
    "museum",
    "park",
    "tourist_attraction",
    "zoo",
    "aquarium",
    # Personal services
    "beauty_salon",
    "hair_salon",
    "spa",
    "gym",
    "laundry",
]
